const roomId = new URLSearchParams(window.location.search).get("room") || "class-3-2";
const storageKey = "king-challenge-host:" + roomId;
const firebaseConfig = {
  apiKey: "AIzaSyBzKPMuRx87I-TvUZugsNSkPPVSu0Yks6g",
  authDomain: "kinggame-fe387.firebaseapp.com",
  databaseURL: "https://kinggame-fe387-default-rtdb.firebaseio.com",
  projectId: "kinggame-fe387",
  storageBucket: "kinggame-fe387.firebasestorage.app",
  messagingSenderId: "265837249346",
  appId: "1:265837249346:web:93ba4bf88792cf6f9f3edb",
  measurementId: "G-10SCNVD4DQ"
};
let databaseApi = null;
let databaseRef = null;
let unsubscribe = null;
const state = { settings: { roomName: "왕좌 도전", games: [], kingLimit: 3, perfectScore: 0, sheetUrl: "", status: "playing", updatedAt: Date.now() }, students: {} };
const els = {
  roomLabel: document.querySelector("#roomLabel"), boardView: document.querySelector("#boardView"), settingsView: document.querySelector("#settingsView"), boardTabButton: document.querySelector("#boardTabButton"), settingsTabButton: document.querySelector("#settingsTabButton"), boardTitle: document.querySelector("#boardTitle"), gamesInput: document.querySelector("#gamesInput"), kingLimitInput: document.querySelector("#kingLimitInput"), perfectScoreLabel: document.querySelector("#perfectScoreLabel"), boardPerfectScoreLabel: document.querySelector("#boardPerfectScoreLabel"), saveSettingsButton: document.querySelector("#saveSettingsButton"), resetButton: document.querySelector("#resetButton"), sheetUrlInput: document.querySelector("#sheetUrlInput"), loadSheetButton: document.querySelector("#loadSheetButton"), saveSheetUrlButton: document.querySelector("#saveSheetUrlButton"), clearStudentsButton: document.querySelector("#clearStudentsButton"), studentForm: document.querySelector("#studentForm"), studentNameInput: document.querySelector("#studentNameInput"), activeCountLabel: document.querySelector("#activeCountLabel"), kingCountLabel: document.querySelector("#kingCountLabel"), kingLimitLabel: document.querySelector("#kingLimitLabel"), studentCountLabel: document.querySelector("#studentCountLabel"), challengerCountLabel: document.querySelector("#challengerCountLabel"), kingList: document.querySelector("#kingList"), scoreBoard: document.querySelector("#scoreBoard"), challengerCarousel: document.querySelector("#challengerCarousel"), attendanceList: document.querySelector("#attendanceList"), emptyTemplate: document.querySelector("#emptyTemplate")
};
els.roomLabel.textContent = roomId;
function showToast(message) {
  const toast = document.createElement("div");
  toast.className = "toast-message";
  toast.textContent = message;
  document.body.appendChild(toast);
  toast.offsetHeight; // trigger reflow
  toast.classList.add("show");
  setTimeout(function(){
    toast.classList.remove("show");
    setTimeout(function(){ toast.remove(); }, 300);
  }, 2500);
}
function playSound(kind){ const AudioContext = window.AudioContext || window.webkitAudioContext; if(!AudioContext) return; const sounds = { click:[360,.06], save:[520,.09], crown:[740,.18], reset:[180,.2] }; const pair = sounds[kind] || sounds.click; const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = kind === "reset" ? "sawtooth" : "sine"; oscillator.frequency.value = pair[0]; gain.gain.setValueAtTime(.001, context.currentTime); gain.gain.exponentialRampToValueAtTime(.18, context.currentTime + .01); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + pair[1]); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + pair[1]); }
function getGamesFromInput(){ return els.gamesInput.value.split("\n").map(function(name){ return name.trim(); }).filter(Boolean).map(function(name,index){ return { id: "game_" + (index + 1), name: name }; }); }
function normalizeStudent(student){ return { id: student.id, name: student.name, number: student.number || "", score: Math.max(0, Number(student.score) || 0), absent: Boolean(student.absent), status: student.status || "normal", crownOrder: student.crownOrder ?? null, challengerOrder: student.challengerOrder ?? null, reachedPerfectAt: student.reachedPerfectAt ?? null, updatedAt: student.updatedAt || Date.now() }; }
function activeStudents(){ return Object.values(state.students).map(normalizeStudent).filter(function(student){ return !student.absent; }); }
function recalculateRanks(nextState){ const perfectScore = nextState.settings.perfectScore; const kingLimit = Math.max(1, Number(nextState.settings.kingLimit) || 1); Object.values(nextState.students).forEach(function(student){ student.status = "normal"; student.crownOrder = null; student.challengerOrder = null; if(student.score < perfectScore || student.absent) student.reachedPerfectAt = null; }); const perfectStudents = Object.values(nextState.students).map(normalizeStudent).filter(function(student){ return !student.absent && student.score >= perfectScore && perfectScore > 0; }).sort(function(a,b){ const aTime = a.reachedPerfectAt || a.updatedAt || 0; const bTime = b.reachedPerfectAt || b.updatedAt || 0; return aTime - bTime || a.name.localeCompare(b.name, "ko"); }); perfectStudents.forEach(function(student,index){ const target = nextState.students[student.id]; if(!target.reachedPerfectAt) target.reachedPerfectAt = Date.now(); if(index < kingLimit){ target.status = "king"; target.crownOrder = index + 1; } else { target.status = "challenger"; target.challengerOrder = index - kingLimit + 1; } }); }
function createDefaultState(){ const now = Date.now(); return { settings: { roomName: "왕좌 도전", games: [{id:"game_1",name:"가위바위보"},{id:"game_2",name:"수학 퀴즈"},{id:"game_3",name:"낱말 맞히기"}], kingLimit: 2, perfectScore: 6, sheetUrl: "", status: "playing", updatedAt: now }, students: {} }; }
function setState(nextState){ state.settings = Object.assign({}, state.settings, nextState.settings || {}); state.students = Object.fromEntries(Object.entries(nextState.students || {}).map(function(entry){ return [entry[0], normalizeStudent(entry[1])]; })); recalculateRanks(state); render(); }
async function saveState(sound){ state.settings.updatedAt = Date.now(); recalculateRanks(state); if(databaseApi && databaseRef){ await databaseApi.set(databaseRef, state); } else { localStorage.setItem(storageKey, JSON.stringify(state)); render(); } playSound(sound || "click"); }
async function setupFirebase(){ if(!firebaseConfig.apiKey || !firebaseConfig.databaseURL) return false; const [appModule, databaseModule] = await Promise.all([ import("https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js"), import("https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js") ]); const app = appModule.initializeApp(firebaseConfig); const database = databaseModule.getDatabase(app); databaseApi = databaseModule; databaseRef = databaseModule.ref(database, "rooms/" + roomId); unsubscribe = databaseModule.onValue(databaseRef, function(snapshot){ const value = snapshot.val(); if(value){ setState(value); } else { setState(createDefaultState()); saveState("save"); } }); return true; }
function loadLocalState(){ const saved = localStorage.getItem(storageKey); if(saved){ setState(JSON.parse(saved)); return; } setState(createDefaultState()); localStorage.setItem(storageKey, JSON.stringify(state)); }
function switchView(view){ const isBoard = view === "board"; els.boardView.classList.toggle("active", isBoard); els.settingsView.classList.toggle("active", !isBoard); els.boardTabButton.classList.toggle("active", isBoard); els.settingsTabButton.classList.toggle("active", !isBoard); playSound("click"); }
function renderSettings(){ els.gamesInput.value = state.settings.games.map(function(game){ return game.name; }).join("\n"); els.kingLimitInput.value = state.settings.kingLimit; els.sheetUrlInput.value = state.settings.sheetUrl || ""; els.perfectScoreLabel.textContent = state.settings.perfectScore + "점"; els.boardPerfectScoreLabel.textContent = state.settings.perfectScore + "점"; els.kingLimitLabel.textContent = state.settings.kingLimit + "자리"; }
function getSortedStudents(){ return activeStudents().sort(function(a,b){ if(a.status === "king" && b.status !== "king") return -1; if(a.status !== "king" && b.status === "king") return 1; if(a.status === "challenger" && b.status === "normal") return -1; if(a.status === "normal" && b.status === "challenger") return 1; return b.score - a.score || a.name.localeCompare(b.name, "ko"); }); }
function statusText(status){ if(status === "king") return "왕"; if(status === "challenger") return "도전자"; return "도전 중"; }
function emptyNode(){ return els.emptyTemplate.content.firstElementChild.cloneNode(true); }
function renderKings(students){ const kings = students.filter(function(student){ return student.status === "king"; }).sort(function(a,b){ return a.crownOrder - b.crownOrder; }); els.kingCountLabel.textContent = kings.length + "명"; els.kingList.replaceChildren(); if(!kings.length){ els.kingList.append(emptyNode()); return; } kings.forEach(function(student){ const card = document.createElement("article"); card.className = "king-card"; card.innerHTML = '<div class="king-name"><span class="crown-mark" aria-hidden="true">♛</span><span>' + student.name + '</span></div><p>' + student.crownOrder + '번째 왕좌 · ' + student.score + '점</p>'; els.kingList.append(card); }); }
function renderScoreBoard(students){ els.activeCountLabel.textContent = students.length + "명"; els.studentCountLabel.textContent = students.length + "명"; els.scoreBoard.replaceChildren(); if(!students.length){ els.scoreBoard.append(emptyNode()); return; } students.forEach(function(student){ const percent = state.settings.perfectScore ? Math.min(100, Math.round((student.score / state.settings.perfectScore) * 100)) : 0; const row = document.createElement("article"); row.className = "student-row"; row.innerHTML = '<div class="student-main">' + (student.status === "king" ? '<span class="crown-mark" aria-hidden="true">♛</span>' : '') + '<span class="student-name">' + student.name + '</span><span class="status-pill ' + student.status + '">' + statusText(student.status) + '</span></div><div class="score-meter"><div class="score-number">' + student.score + ' / ' + state.settings.perfectScore + '점</div><div class="meter-track"><div class="meter-fill" style="width:' + percent + '%"></div></div></div><div class="score-actions"><button class="mini-button" type="button" data-action="plus" data-id="' + student.id + '">+2</button><button class="mini-button" type="button" data-action="minus" data-id="' + student.id + '">-1</button></div>'; els.scoreBoard.append(row); }); }
function renderChallengers(students){ const challengers = students.filter(function(student){ return student.status === "challenger"; }).sort(function(a,b){ return a.challengerOrder - b.challengerOrder; }); els.challengerCountLabel.textContent = challengers.length + "명"; els.challengerCarousel.replaceChildren(); if(!challengers.length){ const empty = document.createElement("div"); empty.className = "challenger-card"; empty.innerHTML = "<strong>대기 중인 도전자가 없습니다.</strong><span>만점자가 더 나오면 이곳에 표시됩니다.</span>"; els.challengerCarousel.append(empty); return; } challengers.forEach(function(student){ const card = document.createElement("article"); card.className = "challenger-card"; card.innerHTML = "<strong>" + student.challengerOrder + ". " + student.name + "</strong><span>" + student.score + "점 · 결전 대기</span>"; els.challengerCarousel.append(card); }); }
function renderAttendance(){ const students = Object.values(state.students).map(normalizeStudent).sort(function(a,b){ return a.name.localeCompare(b.name, "ko"); }); els.attendanceList.replaceChildren(); if(!students.length){ els.attendanceList.append(emptyNode()); return; } students.forEach(function(student){ const row = document.createElement("article"); row.className = "attendance-row" + (student.absent ? " absent" : ""); row.innerHTML = '<div><div class="attendance-name">' + student.name + '</div><p>' + (student.absent ? '결석으로 제외됨' : '전광판에 참여 중') + '</p></div><button class="toggle-button ' + (student.absent ? 'absent' : '') + '" type="button" data-id="' + student.id + '">' + (student.absent ? '결석' : '출석') + '</button>'; els.attendanceList.append(row); }); }
function render(){ renderSettings(); const students = getSortedStudents(); renderKings(students); renderScoreBoard(students); renderChallengers(students); renderAttendance(); }
function upsertStudentsFromNames(names){ const now = Date.now(); const existingByName = new Map(Object.values(state.students).map(function(student){ return [student.name, student]; })); names.forEach(function(name, index){ if(!name) return; const existing = existingByName.get(name); if(existing){ existing.number = existing.number || String(index + 1); existing.updatedAt = now; return; } const id = "student_" + crypto.randomUUID(); state.students[id] = { id:id, name:name, number:String(index + 1), score:0, absent:false, status:"normal", crownOrder:null, challengerOrder:null, reachedPerfectAt:null, updatedAt:now }; }); }
function extractNamesFromSheetData(data){ const source = Array.isArray(data) ? data : (Array.isArray(data.students) ? data.students : []); return source.map(function(item){ if(typeof item === "string") return item.trim(); return String(item.name || item.이름 || item.studentName || item.학생명 || "").trim(); }).filter(Boolean); }
els.boardTabButton.addEventListener("click", function(){ switchView("board"); });
els.settingsTabButton.addEventListener("click", function(){ switchView("settings"); });
els.gamesInput.addEventListener("input", function(){ const gameCount = getGamesFromInput().length; els.perfectScoreLabel.textContent = (gameCount * 2) + "점"; });
els.saveSettingsButton.addEventListener("click", async function(){ const games = getGamesFromInput(); if(!games.length){ alert("게임 종목을 하나 이상 입력해 주세요."); return; } state.settings.games = games; state.settings.kingLimit = Math.max(1, Number(els.kingLimitInput.value) || 1); state.settings.perfectScore = games.length * 2; state.settings.sheetUrl = els.sheetUrlInput.value.trim(); await saveState("save"); showToast("설정이 저장되었습니다."); });
els.saveSheetUrlButton.addEventListener("click", async function(){ state.settings.sheetUrl = els.sheetUrlInput.value.trim(); await saveState("save"); showToast("주소가 저장되었습니다."); });
els.loadSheetButton.addEventListener("click", async function(){ const url = els.sheetUrlInput.value.trim(); if(!url){ alert("Apps Script 주소를 입력해 주세요."); return; } try { const response = await fetch(url); if(!response.ok) throw new Error("명단을 불러오지 못했습니다."); const data = await response.json(); const names = extractNamesFromSheetData(data); if(!names.length){ alert("가져올 학생 이름이 없습니다.\n서버 응답: " + JSON.stringify(data).substring(0, 150)); return; } state.settings.sheetUrl = url; upsertStudentsFromNames(names); await saveState("save"); alert(names.length + "명의 명단을 불러왔습니다."); } catch(error){ alert("명단 불러오기에 실패했습니다. Apps Script 배포 주소와 JSON 형식을 확인해 주세요."); } });
els.clearStudentsButton.addEventListener("click", async function(){ const confirmed = confirm("저장된 모든 학생 명단과 점수를 완전히 삭제하시겠습니까?\n이 작업은 되돌릴 수 없습니다."); if(!confirmed) return; state.students = {}; await saveState("reset"); });
els.resetButton.addEventListener("click", async function(){ const confirmed = confirm("모든 점수와 왕관 상태를 초기화할까요?"); if(!confirmed) return; Object.values(state.students).forEach(function(student){ student.score = 0; student.status = "normal"; student.crownOrder = null; student.challengerOrder = null; student.reachedPerfectAt = null; student.updatedAt = Date.now(); }); await saveState("reset"); });
els.studentForm.addEventListener("submit", async function(event){ event.preventDefault(); const name = els.studentNameInput.value.trim(); if(!name) return; const id = "student_" + crypto.randomUUID(); state.students[id] = { id:id, name:name, number:"", score:0, absent:false, status:"normal", crownOrder:null, challengerOrder:null, reachedPerfectAt:null, updatedAt:Date.now() }; els.studentNameInput.value = ""; await saveState("click"); });
els.scoreBoard.addEventListener("click", async function(event){ const button = event.target.closest("button[data-action]"); if(!button) return; const student = state.students[button.dataset.id]; if(!student || student.absent) return; if(button.dataset.action === "plus"){ const wasPerfect = student.score >= state.settings.perfectScore; student.score += 2; if(!wasPerfect && student.score >= state.settings.perfectScore){ student.reachedPerfectAt = Date.now(); playSound("crown"); } } else { student.score = Math.max(0, student.score - 1); } student.updatedAt = Date.now(); await saveState("click"); });
els.attendanceList.addEventListener("click", async function(event){ const button = event.target.closest("button[data-id]"); if(!button) return; const student = state.students[button.dataset.id]; if(!student) return; student.absent = !student.absent; student.updatedAt = Date.now(); await saveState("click"); });
window.addEventListener("beforeunload", function(){ if(unsubscribe) unsubscribe(); });
setupFirebase().then(function(connected){ if(!connected) loadLocalState(); });